FROM efes
RUN apt-get update && apt-get install -y mysql-client
ADD docker-start-server.sh /root/start-server.sh
ADD docker-wait-for-db.sh /root/wait-for-db.sh
ENTRYPOINT ["/bin/bash", "/root/start-server.sh"]
