FROM rabbitmq:3.6

ARG RABBITMQ_USER=mogilefs
ARG RABBITMQ_PASS=123

ENV HOME=/var/lib/rabbitmq2
ENV RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq2/mnesia
ENV RABBITMQ_NODENAME=efes@localhost

RUN mkdir $HOME
RUN rabbitmq-plugins enable --offline rabbitmq_management
EXPOSE 15671 15672

ADD docker-init-rabbitmq.sh /tmp/
RUN ["bash", "/tmp/docker-init-rabbitmq.sh"]

ENTRYPOINT ["rabbitmq-server", "--hostname", "localhost"]
