FROM mysql:5.7.20

ARG MYSQL_USER=efes
ARG MYSQL_PASSWORD=123
ARG MYSQL_DATABASE=efes

ADD docker-init-mysql.sh /tmp/
ADD schema.sql /tmp/

RUN ["bash", "/tmp/docker-init-mysql.sh"]

ENTRYPOINT ["mysqld", "--user=root", "--datadir=/var/lib/mysql2"]

EXPOSE 3306
