FROM golang:1.9.2 AS builder
WORKDIR /go/src/github.com/putdotio/efes/
RUN go get github.com/golang/dep/cmd/dep
ADD Gopkg.toml Gopkg.lock /go/src/github.com/putdotio/efes/
RUN dep ensure -vendor-only
RUN apt-get update && apt-get install -y mysql-client
ADD docker-run-tests.sh /root/run-tests.sh
ADD docker-wait-for-db.sh /root/wait-for-db.sh
ADD *.go /go/src/github.com/putdotio/efes/
ENTRYPOINT ["/bin/bash", "/root/run-tests.sh"]
