FROM ubuntu:xenial

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install mysql-server-5.7

ARG MYSQL_USER=efes
ARG MYSQL_PASSWORD=123
ARG MYSQL_DATABASE=efes

ADD docker-init-mysql.sh /tmp/
ADD schema.sql /tmp/

RUN ["bash", "/tmp/docker-init-mysql.sh"]

ENTRYPOINT ["mysqld"]

EXPOSE 3306
