FROM efes
RUN apt-get update && apt-get -y install fuse
ADD docker-run-tracker.sh /root/run-tracker.sh
ADD config-docker.toml /etc/efes.toml
ENTRYPOINT ["/bin/bash", "/root/run-tracker.sh"]
EXPOSE 8001
