version: '3.9'
services:
  mysql:
    build:
      dockerfile: ./Docker/mysql/Dockerfile
      context: ..
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: efes
      RABBITMQ_DEFAULT_PASS: 123
      RABBITMQ_NODENAME: efes@localhost
    logging:
      driver: none
  test:
    build:
      dockerfile: ./Docker/test/Dockerfile
      context: ..
    depends_on:
      - mysql
      - rabbitmq
    tty: true
    volumes:
      - ../coverage:/coverage
