version: '3.9'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: efes
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: efes
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: efes
      RABBITMQ_DEFAULT_PASS: 123
      RABBITMQ_NODENAME: efes@localhost
    logging:
      driver: none
  test:
    build:
      dockerfile: ./Docker/test/Dockerfile
      context: ..
    depends_on:
      - mysql
      - rabbitmq
    tty: true
    volumes:
      - ../coverage:/coverage
