name: release
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and copy binary
        run: make build-docker
      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
            files: ./bin/efes